stages:
  - verify
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

verify:
  image: enzief/egreen-ci:latest
  stage: verify
  script:
    - sbt clean headerCheck test:headerCheck scalafmtCheck test:scalafmtCheck scalafmtSbtCheck test
  only:
    - branches

deploy:
  image: alpine/git:latest
  stage: deploy
  script:
    - echo "machine api.heroku.com"   >  ~/.netrc
    - echo "  login $HEROKU_USERNAME" >> ~/.netrc
    - echo "  password $HEROKU_GIT"   >> ~/.netrc
    - echo "machine git.heroku.com"   >> ~/.netrc
    - echo "  login $HEROKU_USERNAME" >> ~/.netrc
    - echo "  password $HEROKU_GIT"   >> ~/.netrc
    - git remote add heroku https://git.heroku.com/egreen.git
    - git push heroku master
  only:
    - master
