image: enzief/docker-sbt:latest

stages:
  - verify
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

verify:
  stage: verify
  script:
    - sbt headerCheck test:headerCheck scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
  only:
    - branches

test:
  stage: test
  script:
    - sbt clean test
  only:
    - branches

deploy:
  stage: deploy
  script:
    - apk --no-cache --update add git
    - echo "machine api.heroku.com"   >  ~/.netrc
    - echo "  login $HEROKU_USERNAME" >> ~/.netrc
    - echo "  password $HEROKU_GIT"   >> ~/.netrc
    - echo "machine git.heroku.com"   >> ~/.netrc
    - echo "  login $HEROKU_USERNAME" >> ~/.netrc
    - echo "  password $HEROKU_GIT"   >> ~/.netrc
    - git remote add heroku https://git.heroku.com/egreen.git
    - git push heroku master
  only:
    - master
