image: openjdk:8-jre-alpine

stages:
  - verify
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SBT_VERSION: 1.1.6
  SBT_HOME: /usr/local/sbt
  GLIBC_VERSION: 2.27-r0

before_script:
  - apk --no-cache --update add bash wget
  - mkdir -p "$SBT_HOME"
  - wget -q --no-check-certificate -O /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub
  - wget -q --no-check-certificate https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$GLIBC_VERSION/glibc-$GLIBC_VERSION.apk
  - apk add glibc-$GLIBC_VERSION.apk
  - rm glibc-$GLIBC_VERSION.apk
  - wget -qO - --no-check-certificate "https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz" | tar xz -C $SBT_HOME --strip-components=1
  - apk del wget
  - export PATH=${PATH}:${SBT_HOME}/bin

verify:
  stage: verify
  script:
    - sbt headerCheck test:headerCheck scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
  only:
    - branches

test:
  stage: test
  script:
    - sbt clean test
  only:
    - branches

deploy:
  stage: deploy
  script:
    - apk --no-cache --update add git
    - echo "machine api.heroku.com"   >  ~/.netrc
    - echo "  login $HEROKU_USERNAME" >> ~/.netrc
    - echo "  password $HEROKU_GIT"   >> ~/.netrc
    - echo "machine git.heroku.com"   >> ~/.netrc
    - echo "  login $HEROKU_USERNAME" >> ~/.netrc
    - echo "  password $HEROKU_GIT"   >> ~/.netrc
    - git remote add heroku https://git.heroku.com/egreen.git
    - git push heroku master
  only:
    - master
